slice_name: "\u0421\u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u043E\u0441\u0442\
  \u0456"
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 8__table
  viz_type: dist_bar
  slice_id: 71
  time_range: No filter
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: "\u0421\u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\
        \u0442\u044C"
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 420
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: "COUNT(\u0421\u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\
      \u0442\u044C)"
    optionName: metric_q4yhl1657l_tugpduj7ozg
    sqlExpression: null
  adhoc_filters: []
  groupby:
  - "\u0421\u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C"
  columns:
  - "\u041E\u0441\u0432\u0456\u0442\u043D\u0456\u0439 \u0441\u0442\u0443\u043F\u0456\
    \u043D\u044C (\u0440\u0456\u0432\u0435\u043D\u044C)"
  row_limit: 10000
  order_desc: true
  color_scheme: supersetColors
  show_legend: true
  rich_tooltip: true
  bar_stacked: true
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  bottom_margin: auto
  x_ticks_layout: auto
  extra_form_data: {}
  dashboards:
  - 5
query_context: "{\"datasource\":{\"id\":8,\"type\":\"table\"},\"force\":false,\"queries\"\
  :[{\"time_range\":\"No filter\",\"filters\":[],\"extras\":{\"having\":\"\",\"where\"\
  :\"\"},\"applied_time_extras\":{},\"columns\":[\"\u0421\u043F\u0435\u0446\u0456\u0430\
  \u043B\u044C\u043D\u0456\u0441\u0442\u044C\",\"\u041E\u0441\u0432\u0456\u0442\u043D\
  \u0456\u0439 \u0441\u0442\u0443\u043F\u0456\u043D\u044C (\u0440\u0456\u0432\u0435\
  \u043D\u044C)\"],\"metrics\":[{\"aggregate\":\"COUNT\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"\u0421\
  \u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":420,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"TEXT\",\"type_generic\"\
  :1,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"COUNT(\u0421\u043F\
  \u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C)\",\"optionName\"\
  :\"metric_q4yhl1657l_tugpduj7ozg\",\"sqlExpression\":null}],\"annotation_layers\"\
  :[],\"row_limit\":10000,\"series_limit\":0,\"order_desc\":true,\"url_params\":{},\"\
  custom_params\":{},\"custom_form_data\":{}}],\"form_data\":{\"datasource\":\"8__table\"\
  ,\"viz_type\":\"dist_bar\",\"slice_id\":71,\"time_range\":\"No filter\",\"metrics\"\
  :[{\"aggregate\":\"COUNT\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"\u0421\u043F\u0435\u0446\u0456\u0430\
  \u043B\u044C\u043D\u0456\u0441\u0442\u044C\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":420,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"TEXT\",\"type_generic\":1,\"\
  verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"COUNT(\u0421\u043F\u0435\u0446\u0456\
  \u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C)\",\"optionName\":\"metric_q4yhl1657l_tugpduj7ozg\"\
  ,\"sqlExpression\":null}],\"adhoc_filters\":[],\"groupby\":[\"\u0421\u043F\u0435\
  \u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C\"],\"columns\":[\"\u041E\
  \u0441\u0432\u0456\u0442\u043D\u0456\u0439 \u0441\u0442\u0443\u043F\u0456\u043D\u044C\
  \ (\u0440\u0456\u0432\u0435\u043D\u044C)\"],\"row_limit\":10000,\"order_desc\":true,\"\
  color_scheme\":\"supersetColors\",\"show_legend\":true,\"rich_tooltip\":true,\"\
  bar_stacked\":true,\"y_axis_format\":\"SMART_NUMBER\",\"y_axis_bounds\":[null,null],\"\
  bottom_margin\":\"auto\",\"x_ticks_layout\":\"auto\",\"extra_form_data\":{},\"dashboards\"\
  :[5],\"force\":false,\"result_format\":\"json\",\"result_type\":\"full\"},\"result_format\"\
  :\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 9b704d48-6735-41d4-b2df-5c0175c6842b
version: 1.0.0
dataset_uuid: c23c0ded-2f9f-45d9-86eb-a145b64fc3c9
