slice_name: "\u0420\u043E\u043A\u0438 \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_scatter
params:
  datasource: 9__table
  viz_type: echarts_timeseries_scatter
  granularity_sqla: "\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\
    \u0447\u0430\u043D\u043D\u044F"
  time_grain_sqla: P1Y
  time_range: No filter
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: "\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\
        \u0430\u043D\u043D\u044F"
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 437
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: TIMESTAMP WITHOUT TIME ZONE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: "COUNT(\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\
      \u0430\u043D\u043D\u044F)"
    optionName: metric_xcrs5h780ea_7gj6wjab7vu
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: "\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u043D\u044F \u043D\
        \u0430\u0432\u0447\u0430\u043D\u043D\u044F"
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 438
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: TIMESTAMP WITHOUT TIME ZONE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: "COUNT(\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u043D\u044F \u043D\
      \u0430\u0432\u0447\u0430\u043D\u043D\u044F)"
    optionName: metric_c9t3p8xb3m8_dicsy9j4ag7
  groupby:
  - "\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\
    \u043D\u044F"
  contributionMode: null
  adhoc_filters: []
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":9,\"type\":\"table\"},\"force\":false,\"queries\"\
  :[{\"time_range\":\"No filter\",\"granularity\":\"\u041F\u043E\u0447\u0430\u0442\
  \u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\",\"filters\":[],\"\
  extras\":{\"time_grain_sqla\":\"P1Y\",\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[\"\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\
  \u0447\u0430\u043D\u043D\u044F\"],\"metrics\":[{\"expressionType\":\"SIMPLE\",\"\
  column\":{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\"\
  :null,\"column_name\":\"\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\
  \u0447\u0430\u043D\u043D\u044F\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":437,\"is_certified\":false,\"is_dttm\":true,\"python_date_format\"\
  :null,\"type\":\"TIMESTAMP WITHOUT TIME ZONE\",\"type_generic\":2,\"verbose_name\"\
  :null,\"warning_markdown\":null},\"aggregate\":\"COUNT\",\"sqlExpression\":null,\"\
  datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"COUNT(\u041F\u043E\
  \u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\
  )\",\"optionName\":\"metric_xcrs5h780ea_7gj6wjab7vu\"},{\"expressionType\":\"SIMPLE\"\
  ,\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"certified_by\"\
  :null,\"column_name\":\"\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u043D\u044F\
  \ \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":438,\"is_certified\":false,\"\
  is_dttm\":true,\"python_date_format\":null,\"type\":\"TIMESTAMP WITHOUT TIME ZONE\"\
  ,\"type_generic\":2,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"COUNT\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"COUNT(\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u043D\u044F\
  \ \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F)\",\"optionName\":\"metric_c9t3p8xb3m8_dicsy9j4ag7\"\
  }],\"orderby\":[[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"\u041F\
  \u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\
  \",\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":437,\"is_certified\":false,\"is_dttm\":true,\"python_date_format\":null,\"\
  type\":\"TIMESTAMP WITHOUT TIME ZONE\",\"type_generic\":2,\"verbose_name\":null,\"\
  warning_markdown\":null},\"aggregate\":\"COUNT\",\"sqlExpression\":null,\"datasourceWarning\"\
  :false,\"hasCustomLabel\":false,\"label\":\"COUNT(\u041F\u043E\u0447\u0430\u0442\
  \u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F)\",\"optionName\"\
  :\"metric_xcrs5h780ea_7gj6wjab7vu\"},false]],\"annotation_layers\":[],\"row_limit\"\
  :10000,\"series_columns\":[\"\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\
  \u0432\u0447\u0430\u043D\u043D\u044F\"],\"series_limit\":0,\"order_desc\":true,\"\
  url_params\":{},\"custom_params\":{},\"custom_form_data\":{},\"is_timeseries\":true,\"\
  time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\":{\"\
  index\":[\"__timestamp\"],\"columns\":[\"\u041F\u043E\u0447\u0430\u0442\u043E\u043A\
  \ \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\"],\"aggregates\":{\"COUNT(\u041F\
  \u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\
  )\":{\"operator\":\"mean\"},\"COUNT(\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\
  \u043D\u044F \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F)\":{\"operator\":\"\
  mean\"}},\"drop_missing_columns\":false}},{\"operation\":\"flatten\"}]}],\"form_data\"\
  :{\"datasource\":\"9__table\",\"viz_type\":\"echarts_timeseries_scatter\",\"granularity_sqla\"\
  :\"\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\u0430\u043D\
  \u043D\u044F\",\"time_grain_sqla\":\"P1Y\",\"time_range\":\"No filter\",\"metrics\"\
  :[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"\u041F\u043E\u0447\u0430\u0442\u043E\
  \u043A \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":437,\"is_certified\"\
  :false,\"is_dttm\":true,\"python_date_format\":null,\"type\":\"TIMESTAMP WITHOUT\
  \ TIME ZONE\",\"type_generic\":2,\"verbose_name\":null,\"warning_markdown\":null},\"\
  aggregate\":\"COUNT\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"COUNT(\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\
  \u0432\u0447\u0430\u043D\u043D\u044F)\",\"optionName\":\"metric_xcrs5h780ea_7gj6wjab7vu\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"\u0417\u0430\u0432\u0435\u0440\u0448\
  \u0435\u043D\u043D\u044F \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":438,\"is_certified\"\
  :false,\"is_dttm\":true,\"python_date_format\":null,\"type\":\"TIMESTAMP WITHOUT\
  \ TIME ZONE\",\"type_generic\":2,\"verbose_name\":null,\"warning_markdown\":null},\"\
  aggregate\":\"COUNT\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"COUNT(\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u043D\u044F\
  \ \u043D\u0430\u0432\u0447\u0430\u043D\u043D\u044F)\",\"optionName\":\"metric_c9t3p8xb3m8_dicsy9j4ag7\"\
  }],\"groupby\":[\"\u041F\u043E\u0447\u0430\u0442\u043E\u043A \u043D\u0430\u0432\u0447\
  \u0430\u043D\u043D\u044F\"],\"contributionMode\":null,\"adhoc_filters\":[],\"order_desc\"\
  :true,\"row_limit\":10000,\"truncate_metric\":true,\"show_empty_columns\":true,\"\
  comparison_type\":\"values\",\"annotation_layers\":[],\"forecastPeriods\":10,\"\
  forecastInterval\":0.8,\"x_axis_title_margin\":15,\"y_axis_title_margin\":15,\"\
  y_axis_title_position\":\"Left\",\"color_scheme\":\"supersetColors\",\"only_total\"\
  :true,\"markerSize\":6,\"show_legend\":true,\"legendType\":\"scroll\",\"legendOrientation\"\
  :\"top\",\"x_axis_time_format\":\"smart_date\",\"rich_tooltip\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"y_axis_format\":\"SMART_NUMBER\",\"y_axis_bounds\":[null,null],\"\
  extra_form_data\":{},\"dashboards\":[],\"force\":false,\"result_format\":\"json\"\
  ,\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: d60d63b8-2a17-42b4-968c-67ee6b12099f
version: 1.0.0
dataset_uuid: 255a815e-f2ca-47c2-902e-bb8a5274eabf
