slice_name: "\u0421\u0435\u0440\u0435\u0434\u043D\u0456 \u0432\u0456\u043A \u0431\u0430\
  \u043A\u0430\u043B\u0430\u0432\u0440\u0456\u0432 \u0437\u0430 \u0444\u0430\u043A\
  \u0443\u043B\u044C\u0442\u0435\u0442\u0430\u043C\u0438"
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 8__table
  viz_type: dist_bar
  time_range: No filter
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: "\u0412\u0456\u043A"
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 423
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: "AVG(\u0412\u0456\u043A)"
    optionName: metric_wyurgoxzhdn_xka3r8yg9m
  adhoc_filters:
  - expressionType: SIMPLE
    subject: "\u041E\u0441\u0432\u0456\u0442\u043D\u0456\u0439 \u0441\u0442\u0443\u043F\
      \u0456\u043D\u044C (\u0440\u0456\u0432\u0435\u043D\u044C)"
    operator: IN
    operatorId: IN
    comparator:
    - "\u0411\u0430\u043A\u0430\u043B\u0430\u0432\u0440"
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_cp8igjg4n8j_zxklcmr0re
  groupby:
  - "\u0421\u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C"
  columns:
  - "\u041E\u0441\u0432\u0456\u0442\u043D\u0456\u0439 \u0441\u0442\u0443\u043F\u0456\
    \u043D\u044C (\u0440\u0456\u0432\u0435\u043D\u044C)"
  row_limit: 10000
  order_desc: true
  color_scheme: supersetColors
  show_legend: true
  rich_tooltip: true
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  bottom_margin: auto
  x_ticks_layout: auto
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":8,\"type\":\"table\"},\"force\":false,\"queries\"\
  :[{\"time_range\":\"No filter\",\"filters\":[{\"col\":\"\u041E\u0441\u0432\u0456\
  \u0442\u043D\u0456\u0439 \u0441\u0442\u0443\u043F\u0456\u043D\u044C (\u0440\u0456\
  \u0432\u0435\u043D\u044C)\",\"op\":\"IN\",\"val\":[\"\u0411\u0430\u043A\u0430\u043B\
  \u0430\u0432\u0440\"]}],\"extras\":{\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[\"\u0421\u043F\u0435\u0446\u0456\u0430\u043B\u044C\u043D\u0456\u0441\
  \u0442\u044C\",\"\u041E\u0441\u0432\u0456\u0442\u043D\u0456\u0439 \u0441\u0442\u0443\
  \u043F\u0456\u043D\u044C (\u0440\u0456\u0432\u0435\u043D\u044C)\"],\"metrics\":[{\"\
  expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"\u0412\u0456\u043A\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":423,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"BIGINT\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"AVG\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"AVG(\u0412\
  \u0456\u043A)\",\"optionName\":\"metric_wyurgoxzhdn_xka3r8yg9m\"}],\"annotation_layers\"\
  :[],\"row_limit\":10000,\"series_limit\":0,\"order_desc\":true,\"url_params\":{},\"\
  custom_params\":{},\"custom_form_data\":{}}],\"form_data\":{\"datasource\":\"8__table\"\
  ,\"viz_type\":\"dist_bar\",\"time_range\":\"No filter\",\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"\u0412\u0456\u043A\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":423,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"BIGINT\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"AVG\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"AVG(\u0412\
  \u0456\u043A)\",\"optionName\":\"metric_wyurgoxzhdn_xka3r8yg9m\"}],\"adhoc_filters\"\
  :[{\"expressionType\":\"SIMPLE\",\"subject\":\"\u041E\u0441\u0432\u0456\u0442\u043D\
  \u0456\u0439 \u0441\u0442\u0443\u043F\u0456\u043D\u044C (\u0440\u0456\u0432\u0435\
  \u043D\u044C)\",\"operator\":\"IN\",\"operatorId\":\"IN\",\"comparator\":[\"\u0411\
  \u0430\u043A\u0430\u043B\u0430\u0432\u0440\"],\"clause\":\"WHERE\",\"sqlExpression\"\
  :null,\"isExtra\":false,\"isNew\":false,\"datasourceWarning\":false,\"filterOptionName\"\
  :\"filter_cp8igjg4n8j_zxklcmr0re\"}],\"groupby\":[\"\u0421\u043F\u0435\u0446\u0456\
  \u0430\u043B\u044C\u043D\u0456\u0441\u0442\u044C\"],\"columns\":[\"\u041E\u0441\u0432\
  \u0456\u0442\u043D\u0456\u0439 \u0441\u0442\u0443\u043F\u0456\u043D\u044C (\u0440\
  \u0456\u0432\u0435\u043D\u044C)\"],\"row_limit\":10000,\"order_desc\":true,\"color_scheme\"\
  :\"supersetColors\",\"show_legend\":true,\"rich_tooltip\":true,\"y_axis_format\"\
  :\"SMART_NUMBER\",\"y_axis_bounds\":[null,null],\"bottom_margin\":\"auto\",\"x_ticks_layout\"\
  :\"auto\",\"extra_form_data\":{},\"dashboards\":[],\"force\":false,\"result_format\"\
  :\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"\
  full\"}"
cache_timeout: null
uuid: ca77bc7f-e108-40e7-adb7-b4ad5a5dd163
version: 1.0.0
dataset_uuid: c23c0ded-2f9f-45d9-86eb-a145b64fc3c9
